// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLlG4iNa-CoaGXu8aYfVwip-igp9rW8YA',
    appId: '1:216734172973:web:cc456339670955714d75a4',
    messagingSenderId: '216734172973',
    projectId: 'adaptnxtapp',
    authDomain: 'adaptnxtapp.firebaseapp.com',
    storageBucket: 'adaptnxtapp.appspot.com',
    measurementId: 'G-QFWP4E1Q0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDm-maEHY2uqmS8v8yMZarTPa3DmIX1M0',
    appId: '1:216734172973:android:8bf3ccfd975314ea4d75a4',
    messagingSenderId: '216734172973',
    projectId: 'adaptnxtapp',
    storageBucket: 'adaptnxtapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9-TMI-dT0QCEv-ybRJVYSsU8OXMxVEBM',
    appId: '1:216734172973:ios:91dba8049ab072764d75a4',
    messagingSenderId: '216734172973',
    projectId: 'adaptnxtapp',
    storageBucket: 'adaptnxtapp.appspot.com',
    iosBundleId: 'com.example.adpatnxtApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9-TMI-dT0QCEv-ybRJVYSsU8OXMxVEBM',
    appId: '1:216734172973:ios:f86723a5eb95a5e24d75a4',
    messagingSenderId: '216734172973',
    projectId: 'adaptnxtapp',
    storageBucket: 'adaptnxtapp.appspot.com',
    iosBundleId: 'com.example.adpatnxtApp.RunnerTests',
  );
}
